language: ruby
rvm:
 - 2.6.4
services:
  - mysql
before_install:
  - cp config/database.yml_example config/database.yml
script:
  - bundle exec rails db:create db:environment:set db:schema:load db:migrate
  - bundle exec rspec
