default: &default
  adapter: mysql2
  database: lib_agregator
  host: localhost
  username: travis
  password:
  port: 3306
  pool: 25
  encoding: utf8

development:
  <<: *default

test:
  <<: *default
  database: lib_agregator_test
