default: &default
  adapter: mysql2
  database: lib_agregator
  host: localhost
  username: root
  password: rfkf,fyz
  port: 3306
  pool: 25
  encoding: utf8

development:
  <<: *default

test:
  <<: *default
  database: lib_agregator_test
