# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01f78c5f8088336384918650c41bfa20ddd38a2b8f175371f85736b405f18fc422a169b16e2444314bd1781142a892cda2db641c466f08806921b540e6c49182

test:
  secret_key_base: e74900a1a219183e1b307c5b01e80059a9d768f2f667791c1f7f38608d6bfc683ec19caaffcd507813df2b9957268781645022ce26a10a16a66fa128075a2fd4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
